# Created by trellis-cli v1.14.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  espaciosutil.org:
    site_hosts:
    - canonical: espaciosutil.org
      redirects:
      - www.espaciosutil.org
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: true
    env:
      db_host: 127.0.0.1
